[package]
name = "wc_awf" # World class ai web Frame
version = "0.1.2"
edition = "2021"
authors = ["world-class-dev support@worldclass-ai.com"]
description = "World Class Autonomous Cross-Platform Engine for Android, iOS, Desktop & WebAssembly"
repository = "https://github.com/world-class-dev/wc_awf"
license = "MIT"
exclude = [
    "target/",
    ".vscode/",
    "tests/",
    "docs/",
]

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "render_benchmark"
harness = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2", optional = true }
console_error_panic_hook = { version = "0.1.7", optional = true }
pyo3 = { version = "0.20", features = ["extension-module", "abi3-py38"], optional = true }
js-sys = { version = "0.3", optional = true }

[dependencies.web-sys]
version = "0.3"
optional = true
features = [
  "console",
  "Window",
  "Document",
  "Element",
  "HtmlCanvasElement",
  "WebGlRenderingContext",
  "CanvasRenderingContext2d",
  "MouseEvent",
  "TouchEvent",
  "Touch",
  "TouchList",
  "Performance",
]

[features]
default = []
python-binding = ["dep:pyo3"]
wasm = ["dep:wasm-bindgen", "dep:js-sys", "dep:web-sys", "dep:console_error_panic_hook"]