[package]
name = "wc_awf" # World class a- web Frame
version = "0.1.1"
edition = "2021"
authors = ["world-class-dev support@worldclass-ai.com"]
description = "Autonomous Cross-Platform Engine for Android, iOS, Desktop & WebAssembly"
repository = "https://github.com/world-class-dev/wc_awf"
license = "MIT"
exclude = [
    "target/",
    ".vscode/",
    "tests/",
    "docs/",
]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2", optional = true }
pyo3 = { version = "0.20", features = ["extension-module", "abi3-py38"], optional = true }

web-sys = { version = "0.3", features = [
    "Window",
    "Document",
    "Element",
    "HtmlCanvasElement",
    "CanvasRenderingContext2d"
] }

[features]
default = []
python-binding = ["dep:pyo3"]
wasm = ["dep:wasm-bindgen"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
    "Window", "Document", "Element", "HtmlCanvasElement", 
    "CanvasRenderingContext2d", "WebGlRenderingContext"
] }
